# Disabled waiting for ready-to-use action
# name: CI
# on: push

# jobs:
#   lost-pixel-update:
#     name: Lost Pixel Update
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node: [18]
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup Node ${{ matrix.node }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node }}
#           cache: "yarn"

#       - name: Install dependencies
#         run: yarn install --frozen-lockfile

#       - name: Build Next app
#         run: yarn build

#       - name: Run Next app
#         run: yarn start &

#       - name: Lost Pixel
#         uses: lost-pixel/lost-pixel@v2.15.0
#         env:
#           LOST_PIXEL_MODE: update

#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v4
#         if: ${{ failure() && steps.lp.conclusion == 'failure' }}
#         with:
#           token: ${{ secrets.GH_TOKEN }}
#           commit-message: update lost-pixel baselines
#           delete-branch: true
#           branch: "lost-pixel-update/${{ github.ref_name }}"
#           title: "Lost Pixel update - ${{ github.ref_name }}"
#           body: Automated baseline update PR created by Lost Pixel
